.\" this is mdoc file
.Dd $Mdocdate$
.Dt dec2bin 1
.Os
.Sh NAME
.Nm dec2bin
.Nd convert  decimal to binary
.\" .Sh LIBRARY
.\" For sections 2, 3, and 9 only.
.\" Not used in OpenBSD.
.Sh SYNOPSIS
.Nm dec2bin
.Ar  decimal_number
.Sh EXAMPLES
.Cm $
.Nm
10
.Dl
  1010
.Dl
.Cm $
.Nm
3384
.Dl
  110100111000
.Sh AUTHOR
 Written by Muhammed Hussam

